name: main

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: ci-main
  cancel-in-progress: true

jobs:
  sast:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - run: semgrep ci
        env:
          SEMGREP_RULES: p/javascript
